# Generated by Django 6.0.5 on 2026-05-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('GK', 'GK'), ('TECH', 'TECH'), ('MOVIES', 'Movies'), ('SPORTS', 'Sports'), ('ENGLISH', 'English'), ('IAS', 'IAS'), ('GATE', 'GATE'), ('PROGRAMMING', 'Programming')], default='GK', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_coins', models.PositiveIntegerField(default=5)),
            ],
            options={
                'indexes': [models.Index(fields=['active'], name='guess_answe_active_a497a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopularityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_answers', to='guess_answer.surveyquestion')),
            ],
            options={
                'unique_together': {('question', 'text')},
            },
        ),
        migrations.CreateModel(
            name='GuessSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_text', models.CharField(max_length=200)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('revealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guess_submissions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='guess_answer.surveyquestion')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'question'], name='guess_answe_user_id_d17c99_idx')],
                'unique_together': {('question', 'user')},
            },
        ),
    ]
