# Generated by Django 5.2.1 on 2026-05-19 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('FIRST_LOGIN', 'First Login'), ('QUIZ_MASTER', 'Quiz Master'), ('COIN_COLLECTOR', 'Coin Collector'), ('REFERRAL_KING', 'Referral King'), ('SPIN_LUCKY', 'Spin Lucky'), ('STREAK_7', '7-Day Streak'), ('STREAK_30', '30-Day Streak')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_url', models.URLField(blank=True, default='')),
                ('coins_reward', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ALL_TIME', 'All Time')], max_length=20)),
                ('category', models.CharField(choices=[('QUIZ', 'Quiz'), ('GUESS', 'Guess Answer'), ('COINS', 'Coins Earned'), ('REFERRALS', 'Referrals')], max_length=20)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['leaderboard_type', 'category', '-score'], name='leaderboard_leaderb_b76059_idx'), models.Index(fields=['period_start', 'period_end'], name='leaderboard_period__140d49_idx')],
                'unique_together': {('user', 'leaderboard_type', 'category', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
