# Generated by Django 5.2.1 on 2026-05-19 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('os_type', models.CharField(blank=True, default='', max_length=20)),
                ('os_version', models.CharField(blank=True, default='', max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprint', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Fingerprint',
                'verbose_name_plural': 'Device Fingerprints',
            },
        ),
        migrations.CreateModel(
            name='FraudCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('cooldown_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_cooldown', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('MULTI_ACCOUNT', 'Multiple Accounts'), ('DEVICE_SPOOFING', 'Device Spoofing'), ('RAPID_CLICKS', 'Rapid Clicks'), ('SUSPICIOUS_PATTERN', 'Suspicious Pattern'), ('DUPLICATE_REFERRAL', 'Duplicate Referral'), ('MANUAL_FLAG', 'Manual Flag')], max_length=30)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField()),
                ('reference_type', models.CharField(blank=True, default='', max_length=60)),
                ('reference_id', models.CharField(blank=True, default='', max_length=80)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_resolved'], name='fraud_fraud_user_id_c56f62_idx'), models.Index(fields=['signal_type', 'created_at'], name='fraud_fraud_signal__da1488_idx')],
            },
        ),
    ]
