from django.urls import path

from .admin_views import (
    AdminAnalyticsView,
    AdminFraudListView,
    AdminFraudResolveView,
    AdminGuessDetailView,
    AdminGuessListView,
    AdminNotificationCreateView,
    AdminOverviewView,
    AdminQuizDetailView,
    AdminQuizListView,
    AdminSessionsView,
    AdminSpinView,
    AdminTaskDetailView,
    AdminTaskListView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserStatusView,
    AdminWalletAdjustView,
    AdminWalletSummaryView,
    AdminWithdrawActionView,
    AdminWithdrawalsListView,
)

urlpatterns = [
    path("overview/", AdminOverviewView.as_view(), name="admin-overview"),
    path("users/", AdminUserListView.as_view(), name="admin-users"),
    path("users/<int:user_id>/", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("users/<int:user_id>/status/", AdminUserStatusView.as_view(), name="admin-user-status"),
    path("wallet/", AdminWalletSummaryView.as_view(), name="admin-wallet-summary"),
    path("wallet/adjust/", AdminWalletAdjustView.as_view(), name="admin-wallet-adjust"),
    path("withdrawals/", AdminWithdrawalsListView.as_view(), name="admin-withdrawals"),
    path("withdrawals/<int:withdraw_id>/", AdminWithdrawActionView.as_view(), name="admin-withdraw-action"),
    path("quiz/", AdminQuizListView.as_view(), name="admin-quiz-list"),
    path("quiz/<int:quiz_id>/", AdminQuizDetailView.as_view(), name="admin-quiz-detail"),
    path("spin/", AdminSpinView.as_view(), name="admin-spin"),
    path("guess/", AdminGuessListView.as_view(), name="admin-guess-list"),
    path("guess/<int:question_id>/", AdminGuessDetailView.as_view(), name="admin-guess-detail"),
    path("tasks/", AdminTaskListView.as_view(), name="admin-tasks-list"),
    path("tasks/<int:task_id>/", AdminTaskDetailView.as_view(), name="admin-tasks-detail"),
    path("fraud/", AdminFraudListView.as_view(), name="admin-fraud-list"),
    path("fraud/<int:signal_id>/resolve/", AdminFraudResolveView.as_view(), name="admin-fraud-resolve"),
    path("notifications/", AdminNotificationCreateView.as_view(), name="admin-notifications"),
    path("analytics/", AdminAnalyticsView.as_view(), name="admin-analytics"),
    path("sessions/", AdminSessionsView.as_view(), name="admin-sessions"),
]
